profile: cover.out

threshold:
  file: 70
  package: 70
  total: 75
      
exclude:
  paths:
    - \.pb\.go$                                         # excludes all protobuf generated files
    - ^pkg/generated                                    # exclude generated code
    - ^pkg/signals                                      # exclude signal handlers from sample controller
    - ^pkg/telemetry                                    # exclude logging and telemetry wrappers
    - hack/*.go                                         # exclude hack folder
    - ^pkg/buildmeta                                    # exclude build metadata
    - pkg/checkpoint/payload/s3_payload_store.go        # exclude plain vendor API wrappers
    - pkg/checkpoint/request/cql_store.go               # exclude plain vendor API wrappers
    - pkg/checkpoint/request/s3_buffer.go               # exclude S3 Buffer tests as they should be covered in the scheduler/SDK e2e pipelines
    - pkg/checkpoint/request/metadata_store.go          # exclude Metadata Store as it requires CqlStore - should be covered in scheduler/SDK e2e pipelines
    - pkg/checkpoint/request/checkpoint_store.go        # exclude Checkpoint Store as it requires CqlStore - should be covered in scheduler/SDK e2e pipelines
