version: '3.3'

services:
  scylla:
    container_name: scylla
    image: scylladb/scylla
    network_mode: host
    command:
      - "--listen-address"
      - "127.0.0.1"
      - "--smp"
      - "1"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
  minio:
    container_name: minio
    hostname: minio-e2e
    image: quay.io/minio/minio
    network_mode: host
    restart: always
    command:
      - server
      - /data
      - "--console-address"
      - ":9123"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9123" ]
      interval: 30s
      timeout: 10s
      retries: 5

  prepare_buckets:
    container_name: minio-setup
    image: quay.io/minio/minio
    network_mode: host
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        mc alias set e2e "http://localhost:9000" minioadmin minioadmin
        mc admin info e2e
        mc mb --ignore-existing e2e/tmp && mc mb --ignore-existing e2e/nexus

  prepare_scylla:
    container_name: scylla-setup
    image: scylladb/scylla
    network_mode: host
    volumes:
      - ./test-resources/storage:/opt/storage
    depends_on:
      scylla:
        condition: service_healthy
    entrypoint:
      - /opt/storage/prepare-scylla.sh