//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024-2026 ECCO Data & AI Open-Source Project Maintainers.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmContainer) DeepCopyInto(out *NexusAlgorithmContainer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmContainer.
func (in *NexusAlgorithmContainer) DeepCopy() *NexusAlgorithmContainer {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmResources) DeepCopyInto(out *NexusAlgorithmResources) {
	*out = *in
	if in.CustomResources != nil {
		in, out := &in.CustomResources, &out.CustomResources
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmResources.
func (in *NexusAlgorithmResources) DeepCopy() *NexusAlgorithmResources {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmRuntimeEnvironment) DeepCopyInto(out *NexusAlgorithmRuntimeEnvironment) {
	*out = *in
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MappedEnvironmentVariables != nil {
		in, out := &in.MappedEnvironmentVariables, &out.MappedEnvironmentVariables
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeadlineSeconds != nil {
		in, out := &in.DeadlineSeconds, &out.DeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaximumRetries != nil {
		in, out := &in.MaximumRetries, &out.MaximumRetries
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmRuntimeEnvironment.
func (in *NexusAlgorithmRuntimeEnvironment) DeepCopy() *NexusAlgorithmRuntimeEnvironment {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmRuntimeEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmSpec) DeepCopyInto(out *NexusAlgorithmSpec) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(NexusAlgorithmContainer)
		**out = **in
	}
	if in.ComputeResources != nil {
		in, out := &in.ComputeResources, &out.ComputeResources
		*out = new(NexusAlgorithmResources)
		(*in).DeepCopyInto(*out)
	}
	if in.SubmissionBehaviour != nil {
		in, out := &in.SubmissionBehaviour, &out.SubmissionBehaviour
		*out = new(NexusAlgorithmSubmissionBehaviour)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeEnvironment != nil {
		in, out := &in.RuntimeEnvironment, &out.RuntimeEnvironment
		*out = new(NexusAlgorithmRuntimeEnvironment)
		(*in).DeepCopyInto(*out)
	}
	if in.ErrorHandlingBehaviour != nil {
		in, out := &in.ErrorHandlingBehaviour, &out.ErrorHandlingBehaviour
		*out = new(NexusErrorHandlingBehaviour)
		(*in).DeepCopyInto(*out)
	}
	if in.DatadogIntegrationSettings != nil {
		in, out := &in.DatadogIntegrationSettings, &out.DatadogIntegrationSettings
		*out = new(NexusDatadogIntegrationSettings)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmSpec.
func (in *NexusAlgorithmSpec) DeepCopy() *NexusAlgorithmSpec {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmStatus) DeepCopyInto(out *NexusAlgorithmStatus) {
	*out = *in
	if in.SyncedSecrets != nil {
		in, out := &in.SyncedSecrets, &out.SyncedSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SyncedConfigurations != nil {
		in, out := &in.SyncedConfigurations, &out.SyncedConfigurations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SyncedToClusters != nil {
		in, out := &in.SyncedToClusters, &out.SyncedToClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmStatus.
func (in *NexusAlgorithmStatus) DeepCopy() *NexusAlgorithmStatus {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmSubmissionBehaviour) DeepCopyInto(out *NexusAlgorithmSubmissionBehaviour) {
	*out = *in
	if in.ShardClusters != nil {
		in, out := &in.ShardClusters, &out.ShardClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkgroupRef != nil {
		in, out := &in.WorkgroupRef, &out.WorkgroupRef
		*out = new(NexusAlgorithmWorkgroupRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmSubmissionBehaviour.
func (in *NexusAlgorithmSubmissionBehaviour) DeepCopy() *NexusAlgorithmSubmissionBehaviour {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmSubmissionBehaviour)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmTemplate) DeepCopyInto(out *NexusAlgorithmTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmTemplate.
func (in *NexusAlgorithmTemplate) DeepCopy() *NexusAlgorithmTemplate {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusAlgorithmTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmTemplateList) DeepCopyInto(out *NexusAlgorithmTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusAlgorithmTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmTemplateList.
func (in *NexusAlgorithmTemplateList) DeepCopy() *NexusAlgorithmTemplateList {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusAlgorithmTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmWorkgroup) DeepCopyInto(out *NexusAlgorithmWorkgroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmWorkgroup.
func (in *NexusAlgorithmWorkgroup) DeepCopy() *NexusAlgorithmWorkgroup {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmWorkgroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmWorkgroupRef) DeepCopyInto(out *NexusAlgorithmWorkgroupRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmWorkgroupRef.
func (in *NexusAlgorithmWorkgroupRef) DeepCopy() *NexusAlgorithmWorkgroupRef {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmWorkgroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusAlgorithmWorkgroupSpec) DeepCopyInto(out *NexusAlgorithmWorkgroupSpec) {
	*out = *in
	if in.CapabilityTags != nil {
		in, out := &in.CapabilityTags, &out.CapabilityTags
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeTaints != nil {
		in, out := &in.NodeTaints, &out.NodeTaints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeAffinities != nil {
		in, out := &in.NodeAffinities, &out.NodeAffinities
		*out = make([]corev1.NodeAffinity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusAlgorithmWorkgroupSpec.
func (in *NexusAlgorithmWorkgroupSpec) DeepCopy() *NexusAlgorithmWorkgroupSpec {
	if in == nil {
		return nil
	}
	out := new(NexusAlgorithmWorkgroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusDatadogIntegrationSettings) DeepCopyInto(out *NexusDatadogIntegrationSettings) {
	*out = *in
	if in.MountDatadogSocket != nil {
		in, out := &in.MountDatadogSocket, &out.MountDatadogSocket
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusDatadogIntegrationSettings.
func (in *NexusDatadogIntegrationSettings) DeepCopy() *NexusDatadogIntegrationSettings {
	if in == nil {
		return nil
	}
	out := new(NexusDatadogIntegrationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusErrorHandlingBehaviour) DeepCopyInto(out *NexusErrorHandlingBehaviour) {
	*out = *in
	if in.TransientExitCodes != nil {
		in, out := &in.TransientExitCodes, &out.TransientExitCodes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.FatalExitCodes != nil {
		in, out := &in.FatalExitCodes, &out.FatalExitCodes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusErrorHandlingBehaviour.
func (in *NexusErrorHandlingBehaviour) DeepCopy() *NexusErrorHandlingBehaviour {
	if in == nil {
		return nil
	}
	out := new(NexusErrorHandlingBehaviour)
	in.DeepCopyInto(out)
	return out
}
