create table nexus.checkpoints_by_host
(
    host                      text,
    lifecycle_stage           text,
    algorithm                 text,
    id                        text,
    PRIMARY KEY ((host), lifecycle_stage, id)
);

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', 'f47ac10b-58cc-4372-a567-0e02b2c3d479','host123', 'NEW');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', '2c7b6e8d-cc3c-4b5b-a3f6-5d7b9e2c7f2a', 'host123', 'BUFFERED');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', '8a0c8aa9-fc9d-4b2e-9c5c-2c8d7f1e7a3f', 'host789', 'RUNNING');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', '550e8400-e29b-41d4-a716-446655440000', 'host999', 'COMPLETED');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', 'c3b7f1e7-9c5c-4b2e-8a0c-8aa9fc9d7f1e','host321', 'FAILED');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', '7f1e8a9c-4d1c-4f5b-a3f7-9c5b1e7b3c8d', 'host654', 'SCHEDULING_FAILED');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', '9c5b1e7b-4d1c-4f5b-a3f7-1e7b3c8d8a9f', 'host987','DEADLINE_EXCEEDED');

INSERT INTO nexus.checkpoints_by_host (algorithm, id, host, lifecycle_stage)
VALUES ('test-algorithm', '4d5b9f2c-1e7b-3c8d-8a9f-4a0c8b1e7b3f', 'host111','CANCELLED');